title: Jon Bake
description: YASB - Yet Another Software Blog (Sigh)
google_analytics: 'UA-39814300-2'
header_buttons:
  - name: Github
    url: 'https://github.com/jonmbake'
    internal: false
  - name: Personal Constitution
    url: personal_constitution
    internal: true
  - name: Resume
    url: '/assets/pdfs/resume.pdf'
    internal: true
  - name: Contact
    url: 'contact.html'
    internal: true
post_tags:
  security:
    name: Web Security
    color: '#b94a48'
