title: Jon Bake
description: YASB - Yet Another Software Blog (Sigh)
google_analytics: 'UA-39814300-2'
header_buttons:
  - name: Github
    url: 'https://github.com/jonmbake'
    internal: false
  - name: Personal Constitution
    url: personal_constitution
    internal: true
  - name: Resume
    url: '/assets/pdfs/resume.pdf'
    internal: true
  - name: Contact
    url: 'contact.html'
    internal: true
post_tags:
  java:
    name: Java
    color: '#65869E'
  javascript:
    name: JavaScript
    color: '#e5bb31'
  security:
    name: Web Security
    color: '#b94a48'
  software_dev:
    name: Software Development
    color: '#EE6F2E'
  walkthroughs:
    name: Walk Throughs
    color: '#28a745'
  sql:
    name: SQL
    color: '#0085B0'
