title: Jon Bake
description: On Software and Personal Development
header_buttons:
  - name: Github
    url: 'https://github.com/jonmbake'
    internal: false
  - name: Personal Development
    url: personal_development
    internal: true
  - name: Notes
    url: notes
    internal: true
  - name: Contact
    url: 'contact.html'
    internal: true
defaults:
  - scope:
      path: "blog"      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
  - scope:
      path: ""      # empty string for all files
      type: notes   # limit to posts
    values:
      layout: note
collections:
  notes:
    output: true
