title: Jon Bake
description: On Software and Personal Development
header_buttons:
  - name: Github
    url: 'https://github.com/jonmbake'
    internal: false
  - name: Personal Constiution
    url: personal_constitution
    internal: true
  - name: Contact
    url: 'contact.html'
    internal: true
exclude:
  - Rakefile
plugins:
  - jekyll-feed
jekyll_compose:
  draft_default_front_matter:
    remember:
      - First sentence should grab reader's attention
      - Keep things simple
      - Use short sentences
      - Get rid of extra words
      - Use object before action sentence structure
    tags:
sass:
    style: compressed
defaults:
  - scope:
      path: "blog"      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
  - scope:
      path: ""      # empty string for all files
      type: notes   # limit to posts
    values:
      layout: note
collections:
  notes:
    output: true
