title: Jon Bake
description: On Software and Personal Development
url: 'https://jonbake.com'
source_url: https://github.com/jonmbake/jonbake.com
header_buttons:
  - name: Posts
    url: posts
  - name: Notes
    url: notes
  - name: Lists
    url: checklists
footer_links:
  - name: Github
    url: 'https://github.com/jonmbake'
    internal: false
  - name: Personal Constiution
    url: personal_constitution
    internal: true
  - name: Contact
    url: 'mailto:jonmbake@gmail.com'
    internal: true
exclude:
  - package.json
  - package-lock.json
  - node_modules
  - Rakefile
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
jekyll_compose:
  draft_default_front_matter:
    remember:
      - First sentence should grab reader's attention
      - Keep things simple
      - Use short sentences
      - Get rid of extra words
      - Use object before action sentence structure
    tags:
defaults:
  - scope:
      path: "blog"
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
  - scope:
      path: ""      # empty string for all files
      type: checklists
    values:
      layout: checklist
  - scope:
      path: ""      # empty string for all files
      type: notes
    values:
      layout: note
collections:
  checklists:
    output: true
  notes:
    output: true
