title: Jon Bake
description: On Software and Personal Development
google_analytics: 'UA-39814300-2'
header_buttons:
  - name: Github
    url: 'https://github.com/jonmbake'
    internal: false
  - name: Personal Constitution
    url: personal_constitution
    internal: true
  - name: Contact
    url: 'contact.html'
    internal: true
